=== manishfullDev/All-Project/Rest_Soap/references/tournament.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	
	<xs:element name="tournament" type="tournamentType"/>
	
	<xs:group name="common-group">
		<xs:sequence>
			<xs:element name="unique-name" type="xs:string"/>
			<xs:element name="sponsorer" type="xs:string"/>
		</xs:sequence>
	</xs:group>
	
	<xs:complexType name="tournamentType">
		<xs:sequence>
			<xs:element name="info" type="infoType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="infoType">
		<xs:sequence>
			<xs:group ref="common-group"/>
			<xs:element name="place" type="xs:string"/>
			<xs:element name="match-date" type="xs:date"/>
			<xs:element name="organizer" type="xs:string"/>
			<xs:element name="teams" type="teamsType"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="teamsType">
		<xs:sequence>
			<xs:element name="team" type="teamType" minOccurs="2" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>


	<xs:complexType name="teamType">
		<xs:sequence>
			<xs:group ref="common-group"/>
			<xs:element name="captain" type="xs:string"/>
			<xs:element name="coach" type="xs:string"/>
		</xs:sequence>
	</xs:complexType>
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/references/tournament.xml
<?xml version="1.0" encoding="UTF-8"?>
<tournament xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/references/tournament.xsd">
	<info>
		<unique-name>Champions Cup</unique-name>
		<sponsorer>Lays</sponsorer>
		<place>hyderabad</place>
		<match-date>2019-07-22</match-date>
		<organizer>Hyderabad Club</organizer>
		<teams>
			<team>
				<unique-name>Secunderabad Team</unique-name>
				<sponsorer>britania</sponsorer>
				<captain>Gourav</captain>
				<coach>Micheal</coach>
			</team>
			<team>
				<unique-name>Hyderabad Team</unique-name>
				<sponsorer>Horlicks</sponsorer>
				<captain>Ravi</captain>
				<coach>Samuel</coach>
			</team>
		</teams>
	</info>
</tournament>
