=== manishfullDev/All-Project/Rest_Soap/extending/trip.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="trip" type="tripType"/>
	<xs:complexType name="tripType">
		<xs:sequence>
			<xs:element name="primary-contact-person" type="xs:string"/>
			<xs:element name="planned-travel-date" type="xs:date"/>
			<xs:element name="passenger" type="xs:int"/>
			<xs:element name="mobile-no" type="xs:string"/>
			<xs:element name="email-address" type="xs:string"/>	
			<xs:element name="package" type="packageType"/>
		</xs:sequence>
	</xs:complexType>
	
	
	<xs:complexType name="packageType">
		<xs:choice>
			<xs:element name="domestic-package" type="domesticPackageType"/>
			<xs:element name="international-package" type="internationalPackageType"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="domesticPackageType">
		<xs:sequence>
			<xs:element name="unique-package-no" type="xs:string"/>
			<xs:element name="package-name" type="xs:string"/>
			<xs:element name="travel-mode" type="xs:string"/>	
		</xs:sequence>
	</xs:complexType>

	
	<xs:complexType name="internationalPackageType">
		<xs:complexContent>
			<xs:extension base="domesticPackageType">
				<xs:sequence>
					<xs:element name="passport-required" type="xs:boolean"/>
					<xs:element name="visa-required" type="xs:boolean"/>
					<xs:element name="visa-on-arrival" type="xs:boolean"/>
					<xs:element name="age-limit" type="xs:boolean"/>
				</xs:sequence>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
	
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/extending/trip.xml
<?xml version="1.0" encoding="UTF-8"?>
<trip xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/extending/trip.xsd">
	<primary-contact-person>mike</primary-contact-person>
	<planned-travel-date>2019-07-30</planned-travel-date>
	<passenger>2</passenger>
	<mobile-no>030383039</mobile-no>
	<email-address>mike@yahoo.com</email-address>
	<package>
		<international-package>
			<unique-package-no>u0393</unique-package-no>
			<package-name>india tour</package-name>
			<travel-mode>air</travel-mode>
			<passport-required>true</passport-required>
			<visa-required>true</visa-required>
			<visa-on-arrival>true</visa-on-arrival>
			<age-limit>false</age-limit>
		</international-package>
	</package>
</trip>
