=== manishfullDev/All-Project/Rest_Soap/attributes/insurance-policy.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="insurance-policy" type="insurancePolicyType"/>
	<xs:complexType name="insurancePolicyType">	
		<xs:sequence>
			<xs:element name="policy-no" type="xs:string"/>
			<xs:element name="policy-holder-name" type="xs:string"/>
			<xs:element name="plan-no" type="xs:string"/>
			<xs:element name="plan-name" type="xs:string"/>
			<xs:element name="tenure" type="xs:int"/>
			<xs:element name="sum-insurred" type="xs:int"/>
			<xs:element name="premium-amount" type="xs:float"/>
		</xs:sequence>
		<xs:attribute name="policy-type" type="policyTypeEnum" use="required"/>
	</xs:complexType>
	<xs:simpleType name="policyTypeEnum">
		<xs:restriction base="xs:string">
			<xs:enumeration value="risk-coverage"/>
			<xs:enumeration value="accidental-coverage"/>
		</xs:restriction>	
	</xs:simpleType>
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/attributes/insurance-policy.xml
<?xml version="1.0" encoding="UTF-8"?>
<insurance-policy xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/attributes/insurance-policy.xsd" policy-type="risk-coverage">
	<policy-no>p303</policy-no>
	<policy-holder-name>Matt</policy-holder-name>
	<plan-no>93</plan-no>
	<plan-name>Jeevan Jyothi</plan-name>
	<tenure>36</tenure>
	<sum-insurred>200000</sum-insurred>
	<premium-amount>1230</premium-amount>
</insurance-policy>
