=== manishfullDev/All-Project/Rest_Soap/groupOccurences/supermarket.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="super-market" type="superMarketType"/>
	<xs:complexType name="superMarketType">
		<xs:sequence>
			<xs:element name="super-market-name" type="xs:string"/>
			<xs:element name="license-no" type="xs:string"/>
			<xs:element name="products" type="productsType"/>
			<xs:element name="total-amount" type="xs:float"/>
			<xs:element name="discount" type="xs:int"/>
			<xs:element name="paid-amount" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>

	
	
	<xs:complexType name="productsType">
		<xs:choice minOccurs="1" maxOccurs="unbounded">
			<xs:element name="grocery" type="groceryType"/>
			<xs:element name="vegetable" type="vegetableType"/>
		</xs:choice>
	</xs:complexType>
	
	<xs:complexType name="groceryType">
		<xs:sequence>
			<xs:element name="grocery-name" type="xs:string"/>
			<xs:element name="units" type="xs:int"/>
			<xs:element name="brand" type="xs:string"/>
			<xs:element name="price" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>
	

	<xs:complexType name="vegetableType">
		<xs:sequence>
			<xs:element name="vegetable-name" type="xs:string"/>
			<xs:element name="quantity" type="xs:int"/>
			<xs:element name="price" type="xs:float"/>
		</xs:sequence>
	</xs:complexType>	
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/groupOccurences/supermarket.xml
<?xml version="1.0" encoding="UTF-8"?>
<super-market xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/groupOccurences/supermarket.xsd">
	<super-market-name>Rantadeep</super-market-name>
	<license-no>3939444</license-no>
	<products>
		<grocery>
			<grocery-name>Dal</grocery-name>
			<units>1</units>
			<brand>Super</brand>
			<price>100</price>
		</grocery>
		
		<vegetable>
			<vegetable-name>brinjal</vegetable-name>
			<quantity>2</quantity>
			<price>100</price>
		</vegetable>
		<grocery>
			<grocery-name>Dal</grocery-name>
			<units>1</units>
			<brand>Super</brand>
			<price>100</price>
		</grocery>
		<vegetable>
			<vegetable-name>brinjal</vegetable-name>
			<quantity>2</quantity>
			<price>100</price>
		</vegetable>
		<grocery>
			<grocery-name>Dal</grocery-name>
			<units>1</units>
			<brand>Super</brand>
			<price>100</price>
		</grocery>
		<grocery>
			<grocery-name>Dal</grocery-name>
			<units>1</units>
			<brand>Super</brand>
			<price>100</price>
		</grocery>
		<grocery>
			<grocery-name>Dal</grocery-name>
			<units>1</units>
			<brand>Super</brand>
			<price>100</price>
		</grocery>
	</products>
	<total-amount>300</total-amount>
	<discount>10</discount>
	<paid-amount>270</paid-amount>
</super-market>
