=== manishfullDev/All-Project/Rest_Soap/choice/payment.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="payment" type="paymentType"/>
	<xs:complexType name="paymentType">
		<xs:sequence>
			<xs:element name="order-no" type="xs:string"/>
			<xs:element name="unique-merchant-no" type="xs:string"/>
			<xs:element name="tx-detail" type="txDetailType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="txDetailType">
		<xs:choice>
			<xs:element name="card" type="cardType"/>
			<xs:element name="cash" type="cashType"/>
		</xs:choice>
	</xs:complexType>
	<xs:complexType name="cardType">
		<xs:sequence>
			<xs:element name="card-no" type="xs:string"/>
			<xs:element name="expiry-date" type="xs:string"/>
			<xs:element name="issued-bank" type="xs:string"/>
			<xs:element name="cvv" type="xs:int"/>		
		</xs:sequence>
	</xs:complexType>

	
	<xs:complexType name="cashType">
		<xs:sequence>
			<xs:element name="amount-paid" type="xs:float"/>			<xs:element name="denomination" type="denominationType"/>		
		</xs:sequence>
	</xs:complexType>



	<xs:complexType name="denominationType">
		<xs:sequence>
			<xs:element name="note" type="noteType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="noteType">
		<xs:sequence>
			<xs:element name="value" type="xs:int"/>
			<xs:element name="count" type="xs:int"/>
		</xs:sequence>
	</xs:complexType>
	
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/choice/payment.xml
<?xml version="1.0" encoding="UTF-8"?>
<payment xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/choice/payment.xsd">
	<order-no>o03</order-no>
	<unique-merchant-no>um3030</unique-merchant-no>
	<tx-detail>
		<card>
			<card-no>9304-3033-3939-2829</card-no>
			<expiry-date>01/22</expiry-date>
			<issued-bank>icici bank</issued-bank>
			<cvv>393</cvv>
		</card>		
	</tx-detail>
</payment>
