=== manishfullDev/All-Project/Rest_Soap/book2.xsd
<?xml version="1.0" encoding="UTF-8"?>
<xs:schema xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="book" type="bookType"/>
	<xs:complexType name="bookType">
		<xs:sequence>
			<xs:element name="isbn" type="xs:string"/>
			<xs:element name="title" type="xs:string"/>	
			<xs:element name="authors" type="authorsType"/>
			<xs:element name="publisher" type="publisherType"/>
		</xs:sequence>
	</xs:complexType>

	<xs:complexType name="authorsType">
		<xs:sequence>
			<xs:element name="author" type="authorType" minOccurs="1" maxOccurs="unbounded"/>
		</xs:sequence>
	</xs:complexType>
	
	<xs:complexType name="authorType">
		<xs:sequence>
			<xs:element name="author-name" type="xs:string"/>
			<xs:element name="dob" type="xs:date"/>		
		</xs:sequence>
	</xs:complexType>

	
	<xs:complexType name="publisherType">
		<xs:sequence>
			<xs:element name="publisher-name" type="xs:string"/>
			<xs:element name="est-date" type="xs:date"/>
		</xs:sequence>
	</xs:complexType>

	
</xs:schema>

=== manishfullDev/All-Project/Rest_Soap/book2.xml
<?xml version="1.0" encoding="UTF-8"?>
<book xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="file:///D:/work/master/webservices/20190417/book2.xsd">
	<isbn>ie93</isbn>
	<title>dbms</title>
	<authors>
		<author>
			<author-name>tananbum</author-name>
			<dob>1970-01-01</dob>
		</author>
	</authors>
	<publisher>
		<publisher-name>pbp</publisher-name>
		<est-date>1970-02-01</est-date>
	</publisher>
</book>
